spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1/testcms?useSSL=false&autoReconnect=true&useUnicode=true&characterEncoding=UTF-8
    type: com.zaxxer.hikari.HikariDataSource
    username: cms
    password: cms
